services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data
    network_mode: host

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    network_mode: host

  seaweedfs:
    image: chrislusf/seaweedfs:3.79
    ports:
      - "8333:8333" # S3 API
      - "8888:8888" # Filer UI
      - "9333:9333" # Master
    volumes:
      - "seaweedfs_data:/data"
      - "./docker/seaweedfs/s3-config.json:/etc/seaweedfs/s3-config.json:ro"
    command: server -s3=true -s3.config=/etc/seaweedfs/s3-config.json -filer=true -dir=/data
    network_mode: host

  mailpit:
    image: axllent/mailpit
    volumes:
      - mailpit_data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    network_mode: host

  spotlight:
    image: ghcr.io/getsentry/spotlight:latest
    ports:
      - "8969:8969"
    network_mode: host

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "4318:4318"    # OTLP HTTP receiver
      - "4317:4317"    # OTLP gRPC receiver
    network_mode: host

  clamav:
    image: clamav/clamav:latest
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/var/lib/clamav
    network_mode: host

volumes:
  postgres_data:
  redis_data:
  mailpit_data:
  seaweedfs_data:
  clamav_data:
    driver: local